### ISSUE TITLE
Speaker2Log not working for me?

### ISSUE THREAD

**Issue by RoboJin** [misyaguziya/VRCT#10]
Everything else work but for some reason Speaker2Log are not working for me at all.

It doesn't translate what other are speaking and transcript it to VRCT. It also does not work on video too. 
I wounder if it how i route my audio
Motherboard Optical->DAC->Headphone

**Comment by ShiinaSakamoto** [comment]
Hello, RoboJin!

We're going to release the feature that allows you to check and change the speaker device on VRCT next. So, we hope it'll help solve the problem with it even a bit!

**Comment by RoboJin** [comment]
Can't wait for it :D

**Comment by ShiinaSakamoto** [comment]
hh umm then, can you check if it show volume bar like this picture?
![スクリーンショット 2024-04-21 072128](https://github.com/misyaguziya/VRCT/assets/68018796/6226c227-a24b-439c-be06-2108d35ed8a5)
*press and activate the speaker icon button

**Comment by RoboJin** [comment]
Yes, it does pick up the audio with the green bar moving but Speaker2Log still show nothing when enable.

**Comment by ShiinaSakamoto** [comment]
Did you try another speaker device if you have? (After you change it, you need to restart VRCT.)

**Comment by RoboJin** [comment]
Yes i have tested routing thru USB port and found out it's working.

Look like a optical bypass has make the feature not working which is weird :<

**Comment by ShiinaSakamoto** [comment]
I'm not sure what a optical bypass is, but yes... actually, there are some devices that not working on Speaker2Log but recognize as just a sound..
For finding and solving the problem, we're gonna add that feature that you can select speaker devices on VRCT. but it'll not solve the problem completely I guess, though. just, at least it'll help for it. we're sorry for that:(

**Comment by RoboJin** [comment]
Don't be sorry and thanks for the help. This is a great free software to use :)
