### ISSUE TITLE
Speaker2Log repetition

### ISSUE THREAD

**Issue by sinneDeeL** [misyaguziya/VRCT#14]
![Screenshot 2024-05-29 120435](https://github.com/misyaguziya/VRCT/assets/87580639/44032f2b-4b60-4490-b255-138392435cb4)
![Screenshot 2024-05-29 120729](https://github.com/misyaguziya/VRCT/assets/87580639/37cc65c4-7616-4068-ae4b-d9a49b7606af)

**Comment by ShiinaSakamoto** [comment]
Hi sinneDeeL, this is not a bug; it's for accuracy. If you are annoyed by it, I recommend setting both the 'Speaker Record Timeout' and 'Speaker Phrase Timeout' to the same number of seconds. This should reduce that behavior a bit.
