### ISSUE TITLE
VR Overlay locks up, freezes Speaker2Log transcription

### ISSUE THREAD

**Issue by CrashCat** [misyaguziya/VRCT#21]
I noticed that the incoming translation would only show on the VR overlay for about 10-15 minutes before it stopped showing up and also did not show on the log window in the main program anymore either, but outgoing chatbox transcription and translation would keep going. With some trial and error I was able to narrow the issue down to a problem with the VR overlay itself.  

Even with translation toggled off, if the other speaker's transcription is being shown on the VR Overlay then after a few minutes it will stop working. This happens regardless of whether it's set to use Whisper or not. If I turn off the fade-out then the last line that it displayed on the overlay will get stuck on screen. No further lines will be shown in the main program window log until I turn off the overlay, then it will resume transcribing as normal again (but I'll have to go look at the main window to see it). 

I'm using SteamVR and also have VRCX running if that makes a difference, though it seems to me like the overlay floats over top of the VRCX without any issue I still should consider a possible collision there and try without VRCX running next time.  

If you have any advice on what I could check on to help you debug the overlay issue let me know. There is an "error.log" in the AppData\Local\VRCT folder but the error showing there is not from when the overlay froze up.

**Comment by CrashCat** [comment]
Tried it some more without VRCX running and the overlay still broke. If there's anything I can do to help you find it let me know. If not no big deal as I can just float the log window instead but the overlay is convenient when it works.

**Comment by misyaguziya** [comment]
Dear @CrashCat 

Thanks for reporting the issue.
Sorry, but we are currently working on a larger update and can't get to this one, so it will take some time to fix the problem.
Please attach the config.json in the VRCT folder if you can (DeepL If you are using Authkey, please delete that part as the Authkey is in the json) as we would like to reproduce the issue you are experiencing.

**Comment by misyaguziya** [comment]
We have released the latest version (2.2.6) that fixes this issue. Please check it out.
(https://github.com/misyaguziya/VRCT/releases/tag/v2.2.6)
