### ISSUE TITLE
「最前面表示」を有効にすると翻訳エンジンを選択できない

### ISSUE THREAD

**Issue by yppmeat** [misyaguziya/VRCT#25]
VRCTで最前面表示を有効にすると翻訳エンジンのドロップダウンリストよりVRCTの画面のほうが前に出てしまい、選択できなくなる。
![image](https://github.com/user-attachments/assets/25023fa2-4969-4d91-b0f0-7dd00df68dab)

**Comment by misyaguziya** [comment]
Dear @yppmeat 
The above features were added in version 3.0.0.
Please check it.

**Comment by ShiinaSakamoto** [comment]
バージョン3になってこの件は確実に直った思うので一旦クローズします！
また何かあればよろしくお願いします。
