### ISSUE TITLE
一旦使用翻译就无响应，语音也无法输入

### ISSUE THREAD

**Issue by FangTianYixiao** [misyaguziya/VRCT#26]
![3631739660c37bbee3ec09e4d9a56fb8](https://github.com/user-attachments/assets/91405b5d-7813-4315-9e8e-dc7a804d08f0)

**Comment by ShiinaSakamoto** [comment]
您做了什么导致它变得无响应？ （无响应）
是打开翻译功能的那一刻吗？
还是在您发送消息的那一刻？

请尝试重新启动VRCT软件，是否还会出现同样的问题？



何をした時に 応答なし になりましたか？（応答なし=无响应）
翻訳機能をオンにした瞬間ですか？
それともメッセージを送信した瞬間ですか？

VRCTソフトウェアの再起動をしてみてください、それでも同じ現象が起きますか？

**Comment by FangTianYixiao** [comment]
在我发消息的那一刻出现了这个问题，无论我几次重启都还是这样 无响应、点击翻译他会卡一段时间，但是发送信息他会直接卡死，这是在点击翻译后发信息，如果不点击翻译直接发消息的话，他不会卡死

**Comment by FangTianYixiao** [comment]
卡=応答なし=无响应

**Comment by ShiinaSakamoto** [comment]
![スクリーンショット 2024-09-30 055105](https://github.com/user-attachments/assets/aa061e84-7f1a-458a-9a33-c60b13031091)
![スクリーンショット 2024-09-30 055255](https://github.com/user-attachments/assets/b118b3bb-db7d-4837-a372-58b966dcff18)

我想检查一下错误日志。
如图所示，从设置屏幕打开存储设置文件的文件夹。在同一层次结构中是否有一个名为“error.log”的文件？
如果存在，请首先仅删除该“error.log”文件。
然后，为了确保安全，请再次重新启动 VRCT 软件。
然后打开翻译并向我们发送消息。
如果变成“无响应”，只需强制退出 VRCT 并重新启动即可。

您能否按照与之前相同的步骤找到“error.log”文件并告知我们内容（如果有）？
注意：该文件可能包含您的Windows用户名等信息，因此请根据需要删除或隐藏该部分。


エラーログを確認したいと思います。
画像のように、設定画面から設定ファイルが格納されているフォルダを開いてください。同じ階層に"error.log"というファイルはありますか？
もしあれば、まずその"error.log"ファイルだけを削除してください。
次に念の為、もう一度VRCTソフトウェアをもう一度再起動してください。
その後、翻訳機能をオンにして、何かメッセージを送信してください。
"応答なし"になりましたら、そのままVRCTを強制終了、再起動してください。

先ほどと同じ手順で"error.log"ファイルを探し、中身があればそれを教えていただけますか？
注意: ファイルの中に、Windowsユーザー名などが含まれている場合がありますので、必要であれば該当部分を削除か、隠してください。

**Comment by FangTianYixiao** [comment]
我找到了这个文件
[error.log](https://github.com/user-attachments/files/17189073/error.log)

**Comment by ShiinaSakamoto** [comment]
嗯...我收到了与 UI 相关的错误，但我不认为这是原因...我会再仔细研究一下，但是
您也可以尝试重新安装 VRCT 软件本身。

ん～‥‥UI関係のエラーは出てますが、それが原因とは思えないですね……。もう少し調べますが、
VRCTソフトウェア自体の再インストールも試してみてください。

**Comment by inkuxuan** [comment]
You might want to test if this is caused by the accessibility of Translation API within mainland China.
That is to say, if the application deals with network operations on the UI thread.

中国本土からの翻訳API接続が悪いかつネット操作がUIと同じスレッドの場合、応答なしの原因となるかもしれません？

**Comment by inkuxuan** [comment]
@FangTianYixiao 尝试第一次使用VRCT的时候挂个梯子，初始化的时候需要从GitHub下载翻译用的模型

**Comment by misyaguziya** [comment]
AIモデルのweightデータは起動時に毎回チェックしています。
- checkCTranslate2Weight()
- checkWhisperWeight()

また動作を見る限り翻訳機能自体は有効にできているので翻訳のAIモデルはロード完了していると思われる。
メッセージ送信時かつ翻訳有効時にこの問題が発生するため、翻訳処理実行時にAIモデルを使用しない場合で発生していると思う。
@FangTianYixiao さんがどの翻訳機能を使用しているか知りたい。
ここは何を使用していますか？

每次启动时都会检查人工智能模型的重量数据。
- checkCTranslate2Weight()
- checkWhisperWeight()

此外，就操作而言，翻译功能本身是可以启用的，因此翻译的人工智能模型被认为已经加载。
由于这个问题发生在发送信息和启用翻译功能时，因此在执行翻译过程时，如果没有使用人工智能模型，就很可能出现这个问题。
我想知道 @FangTianYixiao 使用的是哪种翻译功能。
你在这里用的是什么？
![image](https://github.com/user-attachments/assets/a37f7bff-66d9-4528-9390-eb449a85f5c4)

**Comment by FangTianYixiao** [comment]
可能是因为我这里是中国大陆的原因，更新进度条不动，我正在尝试搞个VPN来进行更新。感谢各位！
![ffd99231473118d851d07d7fab6445be](https://github.com/user-attachments/assets/07087f9c-245d-402d-bfd0-c6777ed1524a)

![c7b30d4cf7dc03117bb4c63265af17af](https://github.com/user-attachments/assets/d256acef-7de8-428e-a5b0-633f83159024)

**Comment by FangTianYixiao** [comment]
> AIモデルのweightデータは起動時に毎回チェックしています。
> 
> * checkCTranslate2Weight()
> * checkWhisperWeight()
> 
> また動作を見る限り翻訳機能自体は有効にできているので翻訳のAIモデルはロード完了していると思われる。 メッセージ送信時かつ翻訳有効時にこの問題が発生するため、翻訳処理実行時にAIモデルを使用しない場合で発生していると思う。 @FangTianYixiao さんがどの翻訳機能を使用しているか知りたい。 ここは何を使用していますか？
> 
> 每次启动时都会检查人工智能模型的重量数据。
> 
> * checkCTranslate2Weight()
> * checkWhisperWeight()
> 
> 此外，就操作而言，翻译功能本身是可以启用的，因此翻译的人工智能模型被认为已经加载。 由于这个问题发生在发送信息和启用翻译功能时，因此在执行翻译过程时，如果没有使用人工智能模型，就很可能出现这个问题。 我想知道 @FangTianYixiao 使用的是哪种翻译功能。 你在这里用的是什么？ ![image](https://private-user-images.githubusercontent.com/53165965/375402008-a37f7bff-66d9-4528-9390-eb449a85f5c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTY0MDAsIm5iZiI6MTcyODkxNjEwMCwicGF0aCI6Ii81MzE2NTk2NS8zNzU0MDIwMDgtYTM3ZjdiZmYtNjZkOS00NTI4LTkzOTAtZWI0NDlhODVmNWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE0MjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhN2U4ODNjZTU3MDY4Y2VmYjVlY2RhYmMyODlmZjEwNjk0Yjg4YmM0MDM4YTQ5NTBhODg5Yjg0NDg2YWE3NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tsBkz3qvPbiC819dwxdXqSwDZry85tTWkMrpnYDaWfg)

还是不行
