### ISSUE TITLE
Overlay (VR) Z-axis rotation problem

### ISSUE THREAD

**Issue by xenz698** [misyaguziya/VRCT#28]
Problem: Z-axis rotation will take X-axis rotation value upon VRCT start up.  So the translation box will be tilted at the Z-axis, which shouldn't be.

How to produce the problem: With Overlay (VR) set to Enabled. the overlay work correctly. If you set the X-axis rotation to any number, you can see the change on the screen correctly, example, if you set the X-axis to -45, you will see the translation box tilted upwards.  If you close VRCT completely and start it up again, you will see the translation box tilted upwards **and to the right side**. but if you check the setting, Z-axis was still set as 0.  

Workaround: Every time I start VRCT, I will have to go to Overlay (VR) setting, just click on Z-axis rotation, set it to any number, and it will fix the problem for the current session. 

What am I expecting: With Z axis rotation value set to 0, upon starting up VRCT, translation box shouldn't be slanted (tilted on the Z-axis).

Attached setting screenshot and effect screenshot. Everything is default **except** the X-axis rotation value was changed.
**NOTE**: the bug only happen when you close the VRCT app and open it again.

![Z-20bug-a](https://github.com/user-attachments/assets/34b072c6-d1e2-4633-8b39-a0321ff7fa7b)
![Z-20bug-b](https://github.com/user-attachments/assets/6155086d-6613-4d3a-9fc2-a40f3362db3b)
![Z-45bug-a](https://github.com/user-attachments/assets/525943f6-41d0-4e96-a3ba-0caca120065e)
![Z-45bug-b](https://github.com/user-attachments/assets/d35d540c-a0a1-494e-9666-203152870a97)

**Comment by misyaguziya** [comment]
Dear @xenz698 

Thanks for reporting the issue.
Now that we've identified the problem and its cause, we'll fix it in time for the next release.

**Comment by misyaguziya** [comment]
@xenz698 I have released v2.2.8 and would like you to update it.

**Comment by xenz698** [comment]
Thank you misyaguziya-san, confirmed problem is fixed. Really appreciate your quick turn-around service 🙇
