### ISSUE TITLE
建议:在ui语言中增加简体中文 UI言語に簡体字中国語を追加することを提案

### ISSUE THREAD

**Issue by Heart-Breezer** [misyaguziya/VRCT#29]
你好，我是冰锐(Breezer),中国软件工程专业的三年级学生。我学过两年日语，非常喜欢 VRC，也对 VRCT 软件很感兴趣，但我发现 UI 语言只有繁体中文，没有简体中文，这对于不懂繁体中文、日语或英语的人来说很困难。如果需要，我们可以提供与当地其他语言相同格式的表格。

Deepl translate:
こんにちは、ブリーザーです。 中国のソフトウェア工学科3年生のブリーザーです。 2年間日本語を勉強したことがあり、VRCがとても好きで、VRCTのソフトウェアにとても興味がありますが、UIの言語が繁体字中国語だけで、簡体字中国語がないことに気がつきました、繁体字中国語や日本語や英語がわからない人には難しいです。 もし必要であれば、ロケールの他の言語と同じフォーマットでフォームを用意することも可能です。

**Comment by Heart-Breezer** [comment]
他に連絡する方法が見つからなかったので、ここにプロポーズを掲載してすみません。

**Comment by ShiinaSakamoto** [comment]
Breezerさん、こんにちは。UIを担当していますShiinaです。簡体字中国語の追加、とても助かります。
現在、UIを大きく改装中で、今の"main/develop"ブランチを参考にして追加していただいたとしても、今後大きく変更や削除があるかもしれません。

もし、それでも良いという場合はお返事ください。
少しでもやりやすいように、フォーマットを用意いたします。


Deepl translate:
你好，Breezer，我叫 Shiina，负责用户界面。 添加简体中文非常有帮助。
我们目前正在对用户界面进行重大改造，因此即使您添加当前的 “main/develop ”分支作为参考，将来也可能会有重大更改或删除。

如果您仍然愿意这样做，请与我们联系。
我们将提供一种格式，使其尽可能简便。

**Comment by Heart-Breezer** [comment]
もちろん、これは僕のメール：nabdarin277@gmail.com

**Comment by ShiinaSakamoto** [comment]
僕が新しくブランチを作り、そこで作業をしてもらおうと思うので、このままここでの会話でも問題ないですよ～！
準備しますのでしばらくお待ち下さい。

**Comment by ShiinaSakamoto** [comment]
"localization_zh_hans"というブランチを作りました。
そちらを参考に編集していただいて、"localization_zh_hans"ブランチにプルリクエストください！

言語キーを"zh_Hans"、UI上は"简体中文"を追加して選択可能状態にしています。
"locales\zh-Hans.yml"を直接修正してください。日本語を勉強したことがあるとのことなので、ja.ymlからコピペしました。

コメントアウトしている部分は、既に削除が決まっている部分です。翻訳していただいてもいいですし、そのままでも結構です（デフォルトで英語が適用されるようになります）。

質問などありましたら、聞いてください！

**Comment by Heart-Breezer** [comment]
我已经pull request了我的提交,其中有错误或不合适的地方请再联系我.
因为我是mac电脑,无法游玩VRChat,所以并没有下载VRCT,也无法测试是否有问题.

pull requestをしました。もしバッグがあれば、ご連絡ください。
私はマックパソコンを使用している、VRChatをすることはできませんので、私はVRCTをダウンロードしない、問題があるかどうかをテストすることはできません。

**Comment by ShiinaSakamoto** [comment]
> https://github.com/misyaguziya/VRCT/pull/31
