### ISSUE TITLE
Feature request: Selectable output device.

### ISSUE THREAD

**Issue by DJFPaul** [misyaguziya/VRCT#7]
I've recently been introduced to VRCT and generally find the app really nice.

However there is one thing i am missing from it, and that is the option to be able to select which output device is used for monitoring, as at the moment it just uses the default system one.

Being able to change the monitored output device would allows the app do be used in more complex setups.
For example a specific virtual audio cable that is just using the game audio.
(E.g. using OBS to capture Game Audio and outputting it on a dedicated device.)
This would mean that listening to background music or videos would not mess with detecting of conversations.

Or you could also specifically have it listen to the VR Headset output instead of the desktop audio without having to switch default audio devices in Windows for more specific audio setups.

This would also open up possible use cases of the app to way more than just VRChat for someone who uses dedicated conversation outputs.
Like community calls on Discord or something like that.

I for example have 2 separate audio devices in use for the PC, one is dedicated as a conversation output.

**Comment by misyaguziya** [comment]
Dear @DJFPaul 

Thanks for the feature request.
Am I correct that you want to select the device for the speaker?
We had implemented that feature a while ago (versionv2.0.0_alpha_3), but we had to omit it due to processing problems and frequent errors.
However, as far as I checked a little, there was an update to the package used, and the error did not occur, so I will consider implementing it.

**Comment by DJFPaul** [comment]
Hello!

Indeed, i mean to be able to select the device for the speaker so that it's not force bound to the default device.

With such feature, i could use OBS to use "Game Audio Capture" and forward that to a virtual output, that i then select that in VRCT.
This would mean only VRChat audio is heard by the application and not for example music i may listen to or a steam/video in the BG.

**Comment by misyaguziya** [comment]
Dear @DJFPaul 

Version 2.2.3 allows selection of Speaker device.
Please check if it is available.
![image](https://github.com/misyaguziya/VRCT/assets/53165965/f7e161b2-c7bf-4467-8050-76f28f2bcc1f)

**Comment by DJFPaul** [comment]
Thank you for that!
I will check it out once i am back from my Japan holiday.
Currently unable to give it a look due to that.

**Comment by misyaguziya** [comment]
I have implemented the feature and will close this issue.
Please let me know if it worked.

**Comment by DJFPaul** [comment]
> I have implemented the feature and will close this issue. Please let me know if it worked.

I (sadly) arrived back home yesterday. 😢 

I gave it a quick test, and the speaker selection works great. 👍
